### ISSUE TITLE
Thanks for the great work!

### ISSUE THREAD

**Issue by QuanyiLi** [Epihaius/procedural_panda3d_model_primitives#1]
Hi,

I learned a lot from your code. Thank you for sharing this. Can I integrate this module into my project: https://github.com/metadriverse/metadrive?

Besides, I have a minor question. I want to generate a 2D card with a set of points representing its polygons. Could you kindly give me some hints to do this?

Thanks!

**Comment by Epihaius** [comment]
Hi!

It would be an honor for me if you were to integrate my code into your project (and maybe to see my name mentioned in the credits)!
我很高兴你喜欢我的工作。

As to your question, I think you should be able to use [Triangulator](https://docs.panda3d.org/1.10/python/reference/panda3d.core.Triangulator#panda3d.core.Triangulator) in combination with the low-level geometry creation functions to generate the 2D card from the polygon data.
I have added a simple, single-poly example below, showing a very complex - yet correctly triangulated - polygon. The code assumes you have a text file containing the vertex coordinates of your polygon, called "poly_coords.txt", similar to the one I have attached to this reply. The coordinates should be listed in either clockwise or counterclockwise order.
Of course this only adds a single polygon, so it will be a bit more work to add multiple polys. But you could probably add multiple polygon data to the text file and separate the data per polygon with a blank line and adapt the code that parses the text file to take this into account.
Let me know if you have any problems with this approach.

Here is the code:

```python
from panda3d.core import *
from direct.showbase.ShowBase import ShowBase
import array


class MyApp(ShowBase):

    def __init__(self):

        ShowBase.__init__(self)

        # set up a light source
        p_light = PointLight("point_light")
        p_light.set_color((1., 1., 1., 1.))
        self.light = self.camera.attach_new_node(p_light)
        self.light.set_pos(5., -10., 7.)
        self.render.set_light(self.light)
        self.disable_mouse()
        self.camera.set_pos(0., -50., 50.)
        self.camera.look_at(-10., 0., 0.)

        triangulator = Triangulator()
        values = array.array("f", [])
        vertex_data = GeomVertexData("poly", GeomVertexFormat.get_v3n3(), Geom.UH_static)

        with open("poly_coords.txt", "r") as coords_file:
            coords = coords_file.readlines()

        for i, coord in enumerate(coords):
            x, y = [float(c) for c in coord.replace("\n", "").split(" ")]
            values.extend((x, y, 0., 0., 0., 1.))
            triangulator.add_vertex(x, y)
            triangulator.add_polygon_vertex(i)

        triangulator.triangulate()
        prim = GeomTriangles(Geom.UH_static)

        for i in range(triangulator.get_num_triangles()):
            index0 = triangulator.get_triangle_v0(i)
            index1 = triangulator.get_triangle_v1(i)
            index2 = triangulator.get_triangle_v2(i)
            prim.add_vertices(index0, index1, index2)

        # add the values to the vertex table using a memoryview;
        # since the size of a memoryview cannot change, the vertex data table
        # already needs to have the right amount of rows before creating
        # memoryviews from its array(s)
        vertex_data.unclean_set_num_rows(len(coords))
        # retrieve the data array for modification
        data_array = vertex_data.modify_array(0)
        memview = memoryview(data_array).cast("B").cast("f")
        memview[:] = values

        geom = Geom(vertex_data)
        geom.add_primitive(prim)
        node = GeomNode("poly_node")
        node.add_geom(geom)
        poly = self.render.attach_new_node(node)
        poly.set_render_mode_wireframe()


app = MyApp()
app.run()
```

And here is the example text file:
[poly_coords.txt](https://github.com/Epihaius/procedural_panda3d_model_primitives/files/11361616/poly_coords.txt)

Good luck with this - and with your project!
祝好！

**Comment by QuanyiLi** [comment]
Hi, Epihaius

Thank you very much for your knid help! It is exactly what I want. I already merge it to my repo with license included. Besides, we will add your name to the acknowledgement section once we release this new project!

Best,
Quayi

**Comment by Epihaius** [comment]
Glad I could help!
And thank you as well!
